### ISSUE TITLE
Initial Draft

### ISSUE THREAD

**Issue by duke79** [open-devs/carefortheliving#1]
## Contributors
  * [LinkedIn post](https://www.linkedin.com/posts/harikesh-singh-22536038_we-are-collaborating-on-an-opensource-project-activity-6789769266380972032-aq7T)

## Scope
* Person in need asks for help in a form
  * Google form? (so that it's easily customisable?)
    * [Embed in the dashboard somehow?](https://support.google.com/a/users/answer/9308623?hl=en#:~:text=Add%20surveys%20and%20forms%20to,Google%20Forms%20in%20Google%20Sites.&text=Feedback%20survey%E2%80%93Get%20feedback%20from,to%20subscribe%20to%20your%20newsletter.)
    * Can exact map location (or PIN?) as input?
  * fields?? thing needed?
  * How to feed the response data to front-end? A back server in the middle?
    * [App Script](https://script.google.com/home)?
* Dashboard displays the feed on a page
  * Filters - region, requirement, ...?
  * FB comment box below every feed item (i.e. requirement)
* Dashboard displays a map of requirements
  * Filters - requirement, ...?
  * Regions by PIN code? Hierarchical?
  * Hovering shows summary
    * Count per requirement?
* Tooltip expands to the feed with filter preselected as region

**Comment by alok722** [comment]
the project moved to https://github.com/carefortheliving/frontend
